# Mathematical Functions in Numpy

In [1]:
#importing the requisite numpy module
import numpy as np

In [2]:
#Computing the mean of an array 
#Lets create a numpy array to start with.

x = np.array([[1,2,3],[4,5,6]])
print("The mean of all elements in the matrix is: ", np.mean(x))

The mean of all elements in the matrix is:  3.5


###### What happens above is:
##### (sum of all elements) / (number of all elements)

In [3]:
#computing the sum

print("The sum of all elements:", np.sum(x))

The sum of all elements: 21


In [4]:
#Also we can specify which axis the sum has to be done here. Either by columns or rows. Let us take an example of a 2-D Array

a = np.array([
    [1,2,3],
    [5,6,7],
    [8,9,10]
])

In [5]:
a.shape  #so here we have a 3x3 matrix

(3, 3)

In [6]:
# Let us add the elements row-wise ( 0 denotes rows & 1 denotes columns in the matrix)
np.sum(a, axis=0)
a.sum(axis=0)  
## Please Note : both above & below code does the same thing. 
##You could use the numpy array object(numpy array) 'a' to do operations o

array([14, 17, 20])

In [7]:
#change the axis to 1 to add the elements column wise
a.sum(axis=1)

array([ 6, 18, 27])

##### same could be done using 3-D array.

In [8]:
b = np.array([[[1,2,3],
               [4,5,6]
              ]])     #a 3-D Array

In [9]:
b.shape

(1, 2, 3)

In [10]:
b.sum(axis=0)   #no elements to add across the same plane.So it remains the same.

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.sum(axis=1)  #addition happens across the 3D plane

array([[5, 7, 9]])

In [12]:
# Let us now transpose the array
print("The normal Matrix :\n", a)

print("\n")

print("The trasposed matrix:\n", a.T)

The normal Matrix :
 [[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


The trasposed matrix:
 [[ 1  5  8]
 [ 2  6  9]
 [ 3  7 10]]


In [13]:
# We could solve linear equations using matrices in numpy. Let us see how to do it.

#Let us take2 equations,

#   2x + 5y = 10
#   -6x - 9y = 5

#convert the equations into matrices. We separate the equations in the LHS & RHS to two separate matrices.

ar1 = np.array([[2,5],[-6,-9]])
ar2 = np.array([10,5])

#
sol = np.linalg.solve(ar1,ar2)  #use numpy linear algorithm solver to input the equation as separate LHS & RHS array.

###### x = -9.58333
###### y = 5.83333

In [14]:
np.dot(ar1,sol)   
#if we see this dot product. It is equal to equations. it multiplies the coefficients with x & y values to get the 
# RHS of the above equation i.e., 10 & 5   :-)

array([10.,  5.])

Read about Numpy broadcasting

https://numpy.org/doc/stable/user/basics.broadcasting.html

Broadcasting is a numpy concept on how it deals with unequal arrays. You could read about it in the numpy website link above.